# Site Configuration for Tooltician.com
# Last War: Survival Strategy Center

# Site Settings
title: "LastWar Tools"
subtitle: "Strategy Center"
name: "Tooltician"
description: "Strategic Command Center for Last War: Survival. Master the battlefield with our comprehensive toolkit. Interactive calculators, strategic guides, and real-time tools to dominate every season."

# URLs
url: "https://www.tooltician.com"
baseurl: ""
repository: "cortega26/LastWar"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Tooltician Team"
  avatar: "/assets/images/avatar.jpg"
  bio: "Master strategists for Last War: Survival. Providing the best tools and guides for competitive gameplay."
  location: "The Battlefield"
  email: "info@tooltician.com"
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/tooltician"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cortega26/LastWar"

# Site Footer
footer:
  links:
    - label: "Discord Community"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/tooltician"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cortega26/LastWar"
    - label: "Buy Me a Coffee"
      icon: "fas fa-fw fa-coffee"
      url: "https://buymeacoffee.com/tooltician"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "

"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: UTC

# Collections
collections:
  calculators:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "main"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "main"
  # _calculators
  - scope:
      path: "_calculators"
      type: calculators
    values:
      layout: calculator
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: false
      sidebar:
        nav: "tools"
  # _guides
  - scope:
      path: "_guides"
      type: guides
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "guides"

# SEO and Analytics
google_analytics: "G-XXXXXXXXXX" # Replace with your GA4 tracking ID
google_adsense: "ca-pub-XXXXXXXXXXXXXXXX" # Replace with your AdSense ID

# Search
search: true
search_full_content: false
search_provider: lunr

# Social Sharing
twitter:
  username: "tooltician"
facebook:
  username: "tooltician"
  app_id: 
  publisher: 
og_image: "/assets/images/site-logo.png"
social:
  type: Organization
  name: Tooltician
  links:
    - "https://twitter.com/tooltician"
    - "https://facebook.com/tooltician"
    - "https://discord.gg/tooltician"
    - "https://github.com/cortega26"

# Site verification (optional)
google_site_verification: 
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# Monetization
# Uncomment and configure these for monetization
# buy_me_a_coffee: tooltician
# kofi: tooltician
# patreon: tooltician
