title: "LastWar Tools"
description: "Strategy Center for Last War: Survival"

# Use the Minimal Mistakes Jekyll theme hosted on GitHub.  Pinning
# to a specific version helps avoid unexpected changes when the theme
# updates.  The dark skin provides a similar look to the original
# LastWar site while still benefiting from the modern design of
# Minimal Mistakes.
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Exclude non‑site files from the build.  These files are only used
# locally and should not be published.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections and defaults can be added here in the future to organise
# posts or other content.  For now we rely on individual pages.
